### ISSUE TITLE
Syslog flooded with "SendSSDPNotify(): truncated output (512>=512)"

### ISSUE THREAD

**Issue by stintel** [miniupnp/miniupnp#133]
My OpenWrt router's log is flooded with message every 30 seconds:
Mon Jul  6 23:49:25 2015 daemon.warn miniupnpd[11652]: SendSSDPNotify(): truncated output (512>=512)
Mon Jul  6 23:49:25 2015 daemon.warn miniupnpd[11652]: SendSSDPNotify(): truncated output (520>=512)
Mon Jul  6 23:49:25 2015 daemon.warn miniupnpd[11652]: SendSSDPNotify(): truncated output (512>=512)
Mon Jul  6 23:49:25 2015 daemon.warn miniupnpd[11652]: SendSSDPNotify(): truncated output (520>=512)
Mon Jul  6 23:49:25 2015 daemon.warn miniupnpd[11652]: SendSSDPNotify(): truncated output (512>=512)
Mon Jul  6 23:49:25 2015 daemon.warn miniupnpd[11652]: SendSSDPNotify(): truncated output (520>=512)

Running version 1.9.20150609

**Comment by RMerl** [comment]
That was actually a bug in Tomato, with its version string being too long.  A recent upstream commit to miniupnpd increased that limit.

**Comment by stintel** [comment]
Nothing to do with Tomato, I am running OpenWrt CC.

The limit is defined at https://github.com/miniupnp/miniupnp/blob/master/miniupnpd/minissdp.c#L43, and as you can see from the warning, it uses that limit.

**Comment by RMerl** [comment]
Looks like Tomato addressed it by shortening their version string instead of increasing that buffer (I remember it was the first solution discussed amongts Tomato devs at the time).  But it was the very same issue:

https://github.com/miniupnp/miniupnp/pull/129

I guess your OpenWRT build also has a pretty long version string, leading to a truncated packet.  Increasing the current default limit of 512 would work, provided the final size does not go beyond any size limit that might be imposed by SSDP specifications.  Another solution would be to reduce the length of the OS_VERSION string (what is it set to at this time?)

**Comment by miniupnp** [comment]
you can increase SSDP_PACKET_MAX_LEN
indeed I guess you have a very long Server: string

**Comment by miniupnp** [comment]
I think is it a good thing to keep SSDP packets length below 512 bytes.

From http://upnp.org/specs/arch/UPnP-arch-DeviceArchitecture-v1.1.pdf
*Note that UDP packets are also bounded in length (perhaps as small as 512 Bytes in some implementations);*

Some Control Point implementers might limit packet size to 512...
