### ISSUE TITLE
Allow changing TTL for SSDP packets in issued by miniupnpnc and minissdpd

### ISSUE THREAD

**Issue by annulen** [miniupnp/miniupnp#140]
Increasing TTL value allows control point to reach UPnP devices in other subnetworks. Note that many UPnP devices and clients (e.g., gssdp-discover) use TTL > 1

**Comment by miniupnp** [comment]
you mean we should add ```setsockopt(s, IPPROTO_IP, IP_MULTICAST_TTL, &ttl, sizeof(ttl)``` ?

**Comment by annulen** [comment]
Yeah

**Comment by annulen** [comment]
Reasonable default could be 3 or 4

**Comment by miniupnp** [comment]
http://upnp.org/specs/arch/UPnP-arch-DeviceArchitecture-v1.1.pdf : 
To limit network congestion, the time-to-live (TTL) of each IP packet for each multicast message SHOULD default to 2 and
SHOULD be configurable. When the TTL is greater than 1, it is possible for multicast messages to traverse multiple routers;
therefore control points and devices using non-AutoIP addresses MUST send an IGMP Join message so that routers will forward
multicast messages to them (this is not necessary when using an Auto-IP address, since packets with Auto-IP addresses will not be
forwarded by routers).

**Comment by annulen** [comment]
Well, in our corporate network (with lots of smart TVs, DLNA servers and other stuff) I can see UPnP devices using TTL values up to 254 (most use 2-4 though).

**Comment by annulen** [comment]
I think miniupnpnc would also benifit from having TTL option in upnpDiscoverDevice()

**Comment by miniupnp** [comment]
see commit 1da63faa4fff5cb30e5d4b848ceef80a292382b9

**Comment by gvanem** [comment]
Sorry to comment on a closed issue. But Winsock2 doesn't like this `setsockopt()`call. Evidently from this trace (IPv4):
```
listdevices.exe 
searching all UPnP devices
Socket error: setsockopt(IP_MULTICAST_TTL,...), 10022
```
According to [MSDN](https://msdn.microsoft.com/en-us/library/windows/desktop/ms738586(v=vs.85).aspx), the optlen *must* be 4.

I've patched this like so in my local copy:
```
--- a/miniupnpc.c 2015-08-26 17:02:10
+++ b/miniupnpc.c 2015-08-26 18:03:12
@@ -383,6 +383,8 @@
        MIB_IPFORWARDROW ip_forward;
 #endif
        int linklocal = 1;
+    int ttl_size = sizeof(ttl);
+    unsigned long _ttl = (unsigned long) ttl;

        if(error)
                *error = UPNPDISCOVER_UNKNOWN_ERROR;
@@ -528,7 +530,11 @@
                return NULL;
        }

-       if(setsockopt(sudp, IPPROTO_IP, IP_MULTICAST_TTL, &ttl, sizeof(ttl)) < 0)
+#if defined(_WIN32)
+    ttl_size = sizeof(DWORD);
+#endif
+
+       if(setsockopt(sudp, IPPROTO_IP, IP_MULTICAST_TTL, &_ttl, ttl_size) < 0)
        {
                /* not a fatal error */
                PRINT_SOCKET_ERROR("setsockopt(IP_MULTICAST_TTL,...)");
```

But I still get a `10022` (WSAEINVAL) on `listdevices -6` due to another error at my end.

**Comment by miniupnp** [comment]
see aba8c3f3d781eb719a0db906f569d06a1d5e0831
