### ISSUE TITLE
MiniSSDPd: repeat M-SEARCH periodically

### ISSUE THREAD

**Issue by annulen** [miniupnp/miniupnp#141]
AFAIU, currently MiniSSDPd performs exactly one M-SEARCH request when it starts and then relies exclusively on NOTIFY requests from devices. However, it's possible to lose consistency this way, e.g. UDP packet for NOTIFY might get lost.

It might be helpful to repeat M-SEARCH requests periodically. It could be triggered by timer inside minissdpd, or "refresh" request issued by unix socket client.

**Comment by tedshroyer** [comment]
This is very easy to do on the unix socket with request type 3 in a loop. I would prefer that this is not added.

If added, please make it easy to disable.

**Comment by miniupnp** [comment]
about NOTIFY being lost :
http://upnp.org/specs/arch/UPnP-arch-DeviceArchitecture-v1.1.pdf
Due to the unreliable nature of UDP, devices SHOULD send the entire set of discovery messages more than once with some delay between sets e.g. a few hundred milliseconds. To avoid network congestion discovery messages SHOULD NOT be sent more than
three times. In addition, the device MUST re-send its advertisements periodically prior to expiration of the duration specified in the CACHE-CONTROL header field; it is RECOMMENDED that such refreshing of advertisements be done at a randomly-distributed
interval of less than one-half of the advertisement expiration time, so as to provide the opportunity for recovery from lost advertisements before the advertisement expires, and to distribute over time the advertisement refreshment of multiple devices on the network in order to avoid spikes in network traffic.

**Comment by miniupnp** [comment]
the way miniSSDPd is designed, if a few NOTIFY packets are lost, it is not important, only one is sufficient :)
