### ISSUE TITLE
IPv6 "pinholes" are not added to lease_file

### ISSUE THREAD

**Issue by atomt** [miniupnp/miniupnp#18]
Title says it all ;-)

When adding firewallopening using WANIPv6FirewallControl the rules does not get persisted to leases file.
Only IPv4 mappings gets saved.

**Comment by noloader** [comment]
@miniupnp,

Please forgive my ignorance since I don't do much work on Windows anymore... Do modern Microsoft products, like Windows 8 and Windows 10, honor the UPnP commands like punching a hole in the Windows firewall?

I read Microsoft's [Writing Secure Code for Windows Vista](http://www.amazon.com/dp/0735623937) guide twice. There's another interface (Win32 API) that's supposed to be used. But the book is older, and I'm wondering if/how things have changed.

**Comment by miniupnp** [comment]
I'm sorry this is offtopic.
And I just don't know.

**Comment by treysis** [comment]
Unfortunately that seems like a lot of work. Not only will you have to write to the file (should be pretty easy), but you would also have to adjust the parsing for IPv4 so that it doesn't get mixed up. And probably in a way to not break too much backwards compatibility.
Like I said, adding seems easy, but I don't feel ready for the parsing part :(

**Comment by chrysn** [comment]
There seems to be two purposes for the lease files: reloading from a lease file (to ensure old leases stay up even after a config change), and introspection from outside (eg. in openwrt's luci-app-upnp, which displays a refreshing table in the router status page).

I can't easily judge the relevance of IPv6 addresses for the former (as it appears to be primarily for the benefit of UPnP, given that PCP clients would use announce-based rapid recovery). Might it be sufficient to export the data in a non-backparseable way just for the benefit of the latter purpose?

**Comment by Neustradamus** [comment]
Any news on it?

**Comment by svenauhagen** [comment]
I have some code for this issue. I will clean it up and send a PR the next days.

**Comment by Neustradamus** [comment]
@svenauhagen: A nice contribution, thanks!
