### ISSUE TITLE
minissdpd sends initial M-SEARCH message on default interface

### ISSUE THREAD

**Issue by miniupnp** [miniupnp/miniupnp#464]
see #457 

on a setup with 2 network interfaces: ens3 and enp1s0.
using the command `$ /usr/sbin/minissdpd -d -i enp1s0`
minissdpd sends the initial SSDP message on ens3 :
```
M-SEARCH * HTTP/1.1
HOST: 239.255.255.250:1900
ST: ssdp:all
MAN: "ssdp:discover"
MX: 3
```

it looks like call to `setsockopt(sudp, IPPROTO_IP, IP_MULTICAST_IF, ...)` is missing

**Comment by miniupnp** [comment]
@hobbieman could you check if #473 fixes it ?

**Comment by hobbieman** [comment]
Hi. I downloaded the zipfile containing the entire miniupnp project from github today.  I compiled it and ran it, but I don't think it is working properly.  I think it is having trouble attaching to the socket during the send operation because I (a) don't see it send the M-SEARCH and (b) I see an error come on the console.  Here is the output:

```
# ./minissdpd -d -i enp1s0
minissdpd[2901]: ssdpDiscover: sendto: Operation not permitted

```
One thing that is interesting is that if I leave it running, despite the issue mentioned above, some of the devices in my network are sending unsolicited NOTIFY requests, so the minissdp sees these and captures them.  It looks like this:

```
# ./minissdpd -d -i enp1s0
minissdpd[2908]: ssdpDiscover: sendto: Operation not permitted
minissdpd[2908]: SSDP request: 'NOTIFY' (2) ssdp:alive nt=upnp:rootdevice
minissdpd[2908]: new device discovered : uuid:Upnp-XXXXXXXXXXXXXX::upnp:rootdevice
minissdpd[2908]: ** i=1 deltadev=0 **
minissdpd[2908]: SSDP request: 'NOTIFY' (2) ssdp:alive nt=uuid:Upnp-XXXXXXXXXXXXXX
minissdpd[2908]: new device discovered : uuid:Upnp-XXXXXXXXXXXXXX
minissdpd[2908]: ** i=1 deltadev=1 **
```
I then tried to run minissdpd on the other network interface (ens3), and saw the same "operation not permitted" error output on the console and still did not see the M-SEARCH sent on the interface either.  But... The devices that were sending NOTIFY on the previous interface (enp1s0, which is on the 10.10.10.x network) were still doing that, and the daemon still saw those messages, which seems wrong because we were supposed to be using ens3, right?   Here is the output:

```
# ./minissdpd -d -i ens3
minissdpd[2905]: ssdpDiscover: sendto: Operation not permitted
minissdpd[2905]: peer 10.10.10.151:63644 is not from a LAN
minissdpd[2905]: ** i=0 deltadev=0 **
minissdpd[2905]: peer 10.10.10.151:63644 is not from a LAN
minissdpd[2905]: ** i=0 deltadev=0 **
```
So, either the issue remains or I failed to pull down the fix in the zip file. :-(

**Comment by hobbieman** [comment]
Indeed I had not done that.  Thanks for sending me the instructions.  I downloaded the correct branch now, compiled and tested it. The fix works. Thanks!
