### ISSUE TITLE
Stun server periodic wanipcheck on cgnat connection

### ISSUE THREAD

**Issue by professor-jonny** [miniupnp/miniupnp#523]
I guess there is otherways to acomplish by creating a cronjob to restart he upnp server periodically but I'm wondering if miniupnpd could query the Wan IP address or the stun server periodically to update the Wan address from time to time?

This would be more usefull on connections with a cgnat as the upstream IP address could change without warning as the users router is provided with a private ip address and there is no notice of the change to the Wan address.
this happens from time to time expecially with a celular roaming connection or from band hopping.

**Comment by pali** [comment]
upnp protocol was not designed for cgnat setups. I think that if applications needs to know public ip address they should retrieve public ip address on their own and do not use upnp protocol for it. It is too fragile because as you said public ip address may change at anytime and without notice.

also more common cgnat setup is that cgnat server has more public ip addresses and for every outgoing connection is using random public ip address (e.g. round robin). thefore even period checking by miniupnpd would not help...

**Comment by professor-jonny** [comment]
I set up an older version and found it seemed to forward ports as it should but with changes to the WanIP at the cgnat caused ports to be opened in the firewall but appear as closed to the outside network, restarting the upnp service fixed the problem.

Yes many cgnat's use dual public IP addresses to aviod conflicts for users this is where a periodic stun would re address this issue I guess.
