### ISSUE TITLE
miniupnpd - Failed to init redirection engine - Debian 11

### ISSUE THREAD

**Issue by fegauthier** [miniupnp/miniupnp#580]
Hi guys!

I'm using VyOS 1.4 (which is Debian 11 with nftables). I compiled miniupnpd with success but everytime I want to start the process, i got this error. I don't know why. Does anybody have some clues about the issue?

```
miniupnpd[49644]: system uptime is 112133 seconds
miniupnpd[49644]: mnl_socket bound, port_id=49644
miniupnpd[49644]: send_batch: mnl_cb_run returned -1
miniupnpd[49644]: table_op(0, 1, miniupnpd) send_batch failed -4
miniupnpd[49644]: Failed to init redirection engine. EXITING
```

Thanks!

**Comment by miniupnp** [comment]
it is `table_op(NFT_MSG_NEWTABLE, NFPROTO_INET, nft_table);` that fails

**Comment by fegauthier** [comment]
@miniupnp Thanks! I already knew that the problem came from the table_op methods. The things that I don't know is why it fail? What could do this method to fail? Do you have any idea?

**Comment by fegauthier** [comment]
The issue comes from send_batch method. mnl_cb_run() method returns -1 but I don't know why. Do you have an idea?

```
int
send_batch(struct mnl_nlmsg_batch *batch)
{
	int ret;
	ssize_t n;
	char buf[MNL_SOCKET_BUFFER_SIZE];

	mnl_nlmsg_batch_next(batch);

	nft_mnl_batch_put(mnl_nlmsg_batch_current(batch), NFNL_MSG_BATCH_END, mnl_seq++);
	mnl_nlmsg_batch_next(batch);

	if (mnl_sock == NULL) {
		log_error("netlink not connected");
		return -1;
	}

	n = mnl_socket_sendto(mnl_sock, mnl_nlmsg_batch_head(batch),
	                      mnl_nlmsg_batch_size(batch));
	if (n == -1) {
		log_error("mnl_socket_sendto() FAILED: %m");
		return -2;
	}
	mnl_nlmsg_batch_stop(batch);

	do {
		n = mnl_socket_recvfrom(mnl_sock, buf, sizeof(buf));
		if (n == -1) {
			log_error("mnl_socket_recvfrom() FAILED: %m");
			return -3;
		} else if (n == 0) {
			break;
		}
		ret = mnl_cb_run(buf, n, 0, mnl_portid, NULL, NULL);
		if (ret <= -1 /*== MNL_CB_ERROR*/) {
			syslog(LOG_ERR, "%s: mnl_cb_run returned %d",
			       "send_batch", ret);
			return -4;
		}
	} while (ret >= 1 /*== MNL_CB_OK*/);
	/* ret == MNL_CB_STOP */
	return 0;
}
```

**Comment by svenauhagen** [comment]
Hi,

it works fine on stock Debian 11 so it must be something in connection with VyOS or your setup.
Have you made sure that all the necessary netfilter modules are loaded?

Best
Sven

**Comment by miniupnp** [comment]
I don't know if there is a way to get a more explicit error return from `mnl_cb_run()`. All I know is that it returns -1 for errors .

**Comment by svenauhagen** [comment]
I don't know either. The easiest might be to debug the netlink message:

# create the network interface
ip link add  nlmon0 type nlmon
ip link set dev nlmon0 up
tcpdump -i nlmon0 -w netlink.pcap # capture your packets

# Run miniupnpd

wireshark netlink.pcap # look at the results with wireshark

**Comment by miniupnp** [comment]
no response from @fegauthier, closing.

**Comment by burk3** [comment]
I'm having this issue as well. What should I be looking for in the pcap?

At a glance, I see some messages of type "Error" with an error code indicating `Error code: No such file or directory (-ENOENT) (-2)`. That's about the only thing I understand.

I've attached the pcap in case it helps. If there's anything else I can provide, let me know.
[netlink.pcap.gz](https://github.com/miniupnp/miniupnp/files/11999115/netlink.pcap.gz)

**Comment by svenauhagen** [comment]
@burk3 what does your nftables config look like?
Can you share nft list ruleset?

**Comment by burk3** [comment]
@svenauhagen  surely! I've also included the generated miniupnp.conf in the gist as well in case that becomes relevant. https://gist.github.com/burk3/82fbe4bf31d148d0f606fb3c18f3a205

also I _just_ noticed something different between my miniupnpd logs and the OPs: rather than seeing a failure in `table_op(...)` my logs are whining about `nft_send_rule(...)`. e.g.:

```
Jul 11 20:34:48 rae miniupnpd[130041]: NAT-PMP port mapping request : 0->192.168.12.35:41641 udp lifetime=7200s
Jul 11 20:34:48 rae miniupnpd[130041]: UPnP permission rule 0 matched : port mapping accepted
Jul 11 20:34:48 rae miniupnpd[130041]: Check protocol udp for port 41641 on ext_if eth0 73.70.118.XX, 17764649
Jul 11 20:34:48 rae miniupnpd[130041]: send_batch: mnl_cb_run returned -1
Jul 11 20:34:48 rae miniupnpd[130041]: nft_send_rule(0x5648f81edfa0, 6, 2) send_batch failed -4
Jul 11 20:34:48 rae miniupnpd[130041]: Failed to add NAT-PMP 41641 udp->192.168.12.35:41641 'NAT-PMP 41641 udp'
```

Should I open a new issue given the different call that's erroring?

**Comment by burk3** [comment]
The ENOENT from the netlink dump has me very curious. Looking more into the tables/chains/etc miniupnpd expects and how it interacts with them, one thing that stood out was miniupnpd (both the C code and the scripts) is hardcoded to use the `inet` table family (if I am reading the source properly) while the tables on my system are all either `ip` or `ip6`. E.g. all rules generated in [`nftnlrdr.c`](https://github.com/miniupnp/miniupnp/blob/a765292fd77afdfc291c17999568c5b5dcb363c7/miniupnpd/netfilter_nft/nftnlrdr.c#L223) supply only `NFTPROTO_INET` to the rule generating funcs.

Reading through `man nft` it seems "The inet address family is a dummy family which is used to create hybrid IPv4/IPv6 tables." If they are indeed a separate type of table from ip and ip6, I'd wager that the ENOENT is the kernel telling us that the table we're trying to update (table named "filter" with "inet" family) doesn't exist.

[Here](https://git.kernel.org/pub/scm/linux/kernel/git/netdev/net.git/commit/?id=8509f62b0b07) is an example of the NF devs changing the API to return ENOENT in a similar situation.

I think I can test this hypothesis by changing the hardcoded family to IP, building a binary, and running it on this system. Though I'd probably be better off getting it to repro on a vanilla debian box so I can also learn some nftables stuff

**Comment by burk3** [comment]
A confounding factor/outright cause of the above is probably VyOS using it's own systemd unit for miniupnpd which does _not_ call any of the `/etc/miniupnpd/` scripts to get the tables into the expected state. VyOS only installs `miniupnpd-nftables`, which comes with the daemon and only the `nft_*.sh` scripts; `miniupnpd_functions.sh`, the systemd unit, and some other supporting scripts only come with the `miniupnpd` package which VyOS does _not_ install.

I guess another fix might be to have the systemd unit properly call these setup/teardown scripts so that the appropriate tables/chains exist, but I don't really know what the consequences would be of adding such a table to my ruleset. I already have
```
table ip filter {
        chain INPUT {
                type filter hook input priority 0; policy accept;
        }

        chain FORWARD {
                type filter hook forward priority 0; policy accept;
        }
}
table ip6 filter {
        chain INPUT {
                type filter hook input priority 0; policy accept;
        }

        chain FORWARD {
                type filter hook forward priority 0; policy accept;
        }
}
```

which I suspect VyOS is setting up. Will a similar `table ip filter {...}` for use by miniupnpd cause issues? Also I see `policy deny;` everywhere in the script while the corresponding rules/chains from VyOS have `policy accept;`: will miniupnpd be affected with `policy accept;` in those places?

**Comment by svenauhagen** [comment]
You need to use the inet chain it combines ip and ip6 otherwise miniupnpd is not working.
Well policy accept basically accepts everything so you have no firewall feature unless you define some drop rules.
One part of miniupnpd is to add firewall rules based on devices who need it but this part is then useless as everything is allowed anyways. You should check if that is what you want as you are exposing everything to incoming and outgoing traffic.
