### ISSUE TITLE
What is the status of IPv6 PCP in miniupnpd and clients?

### ISSUE THREAD

**Issue by mailinglists35** [miniupnp/miniupnp#597]
I write here because registration on forums doesn't send me the confirmation email.

**First I want to big thank you for this project.** It is essential for good working of my lan client apps that need to open ports in the router! In fact, I believe for me the lack of clear ipv6 equivalent of ipv4 nat-pmp **is the main reason that I am still holding back from moving to ipv6 at home**, even if my isp has enabled it.

What is the status of ipv6 port control protocol in miniupnpd and in clients such as web browsers and torrent applications?

does it work out of the box using versions shipped in most popular linux distributions such as debian-based (ubuntu latest) or rhel-based (fedora latest), or does it need manual compilation of latest github commit?

even if miniupnpd works, are the clients ready for it, like chrome/firefox and deluge/tixati/transmission?

thanks

**Comment by miniupnp** [comment]
I just can't answer instead of the debian/ubuntu package maintainers and instead of web browser and torrent client developers.

miniupnpd is supposed to support IPV6 PCP, please fill issues here if something doesn't work for you.
https://github.com/miniupnp/miniupnp/blob/master/miniupnpd/pcpserver.c#L34
